apiVersion: v1
entries:
  waar:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-24T21:09:19.3202131Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: f393c6413b4416e2355b0c1d63e56e85a0bbeddc360339172d516ee645e55ea4
    home: waar.zaakonline.nl
    icon: waar.zaakonline.nl
    name: waar
    urls:
    - waar-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-24T21:09:19.3118677Z"
