apiVersion: v1
entries:
  waar:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-26T11:21:56.0441466Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: b23036c5bc2516eb5f327a96d0e9baa6f86811c6946f687c38e40d261f1feafe
    home: waar.zaakonline.nl
    icon: waar.zaakonline.nl
    name: waar
    urls:
    - waar-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-26T11:21:56.0394122Z"
