apiVersion: v1
entries:
  waar:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-17T14:52:35.0190902Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 9001335b3c88da01a4e11c274a92a025d48f4b2102d3cacb0c0c64292cf632c4
    home: waar.zaakonline.nl
    icon: waar.zaakonline.nl
    name: waar
    urls:
    - waar-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-17T14:52:35.0089668Z"
