apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-dependencies
  labels:
    {{- include "template.labels" . | nindent 4 }}
stringData:
    dependencies.yaml: |
        parameters:
            {{- if and .Values.security.jwt.id .Values.security.jwt.privateKey }}
            jwt:
                id: {{ .Values.security.jwt.id | quote }}
                privateKey: {{ .Values.security.jwt.privateKey | quote }}
            {{- end }}

            {{- if .Values.security.dependencies }}
            components:
{{ .Values.security.dependencies | toYaml | indent 16 }}
  {{- end }}
